### ISSUE TITLE
Advance OIDN feature

### ISSUE THREAD

**Issue by Endertainer007** [MohamadZeina/blender_instant_denoise#4]
So I just found this interesting video about the Intel open image denoiser. And I think it could be a good feature to be added to this addon. here's the link:
https://www.youtube.com/watch?v=sLLndwUPUiw&list=PLnZydHYu7CAwCzv-bVnlCYI23MC2kwgOr&index=116&t=0s
It's about the advanced method of using the Intel open image denoiser. It would be cool if this feature is added to the addon. I think something like an advanced denoise button to enable it. Overall, I hope this could be added. It would be very helpful for those who use this addon. #4

**Comment by MohamadZeina** [comment]
Oh awesome, thanks very much for the suggestion. This should be pretty straightforward to implement, so I'll do my best to add it soon.

**Comment by MohamadZeina** [comment]
I just implemented this, would love to get your thoughts on it! 

Thanks again for the suggestion, results seem better. Just note that because this applies the denoising node many more times, the compositing step ends up taking considerably longer.

**Comment by Endertainer007** [comment]
Thanks. The addon works well. Here's the result.
(This is my personal project using 128 samples with adaptive sampling. I'm
using the advance denoise feature in this render)
[image: Advance denoised.png]

**Comment by MohamadZeina** [comment]
thanks for getting back. unfortunately I can't see the image, maybe because it doesn't work for e-mail replies? do you mind trying to send it again, I would love to see your result

**Comment by Endertainer007** [comment]
Here's the render result.
(128 samples with adaptive sampling using advance denoise)
[image: Advance denoised.png]
And here's the node setup. I labeled it for you.
[image: Screenshot from 2020-06-16 07-00-00.png]
You know, as a suggestion. I think it would be nice to frame the advance
denoise nodes just so it doesn't look messy. And here's a zip file
containing my project if you want to see it and the two images above just
in case if you can't see the two images above. The project is actually for
testing a fire effect for my animation. It's based on this tutorial:
https://www.youtube.com/watch?v=1mJr6LDtbEM&list=PLnZydHYu7CAwCzv-bVnlCYI23MC2kwgOr&index=29&t=0s

**Comment by Endertainer007** [comment]
Oops, I forgot the zip file. Here it is.
 Camfire_project_denoised.zip
<https://drive.google.com/file/d/1tNv3xj0HpJ5Iso64v2l1QMvj7YPe4uu5/view?usp=drive_web>

**Comment by MohamadZeina** [comment]
Unfortunately the zip file is locked, so I can't access it.

Framing the nodes would be nice, but I think the majority of people using this will not be going into compositing view at all, so I won't be implementing this now. Feel free to make a pull request if you implement this, I would love to get some other users helping out on this project.
